class CreateCvs < ActiveRecord::Migration[5.1]
  def change
    create_table :cvs do |t|
      t.string :name
      t.string :address
      t.string :city
      t.string :postcode
      t.string :phone
      t.string :email
      t.date :birth
      t.string :nationality
      t.string :facebook
      t.string :linkedin
      t.string :degree
      t.string :uni
      t.string :grade
      t.date :year
      t.string :degree1
      t.string :uni1
      t.string :grade1
      t.date :year1
      t.string :degree2
      t.string :uni2
      t.string :grade2
      t.date :year2
      t.string :degree3
      t.string :uni3
      t.string :grade3
      t.date :year3
      t.string :degree4
      t.string :uni4
      t.string :grade4
      t.date :year4
      t.string :degree5
      t.string :uni5
      t.string :grade5
      t.date :year5
      t.string :company
      t.string :jobtitle
      t.date :start
      t.date :end
      t.text :detail
      t.string :company1
      t.string :jobtitle1
      t.date :start1
      t.date :end1
      t.text :detail1
      t.string :company2
      t.string :jobtitle2
      t.date :start2
      t.date :end2
      t.text :detail2
      t.string :company3
      t.string :jobtitle3
      t.date :start3
      t.date :end3
      t.text :detail3
      t.string :skill
      t.string :level
      t.string :skill1
      t.string :level1
      t.string :skill2
      t.string :level2
      t.string :skill3
      t.string :level3
      t.string :skill4
      t.string :level4
      t.string :skill5
      t.string :level5
      t.string :skill6
      t.string :level6
      t.string :skill7
      t.string :level7
      t.string :skill8
      t.string :level8
      t.string :skill9
      t.string :level9
      t.string :language
      t.string :levela
      t.string :language1
      t.string :levelb
      t.string :language2
      t.string :levelc
      t.string :language3
      t.string :leveld

      t.timestamps
    end
  end
end
